import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useReadContract } from 'wagmi';
import abi from "../abi.json";
import { useEffect, useState } from 'react';
import Navbar from '../components/navbar';
import Body from '../components/body';


const Home: NextPage = () => {
  const [value, setValue] = useState("")
  const myReadContract1 = useReadContract({
    abi,
    address: "0xE703F0692547C13c0FA5B13A78aE833232A0Ac5a",
    functionName: 'balanceOf',
    args: ['0x03A71968491d55603FFe1b11A9e23eF013f75bCF'],
  })

  useEffect(() => {
    setValue(String(myReadContract1.data))
  }, [myReadContract1.data])

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <nav>
        <Navbar />
        <ConnectButton />
      </nav>
      <div className={styles.main}>
        <Body />
      </div>
      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
};

export default Home;
